### ISSUE TITLE
Bookmarks disappear after a while in bookmark panel

### ISSUE THREAD

**Issue by garymcnulty** [JeffryBooher/brackets-bookmarks-extension#10]
When I have the bookmark panel open for a while my bookmarks just disappear. The links remain in the preferences json file but don't show up in the bookmark panel or in the css window.

**Comment by JeffryBooher** [comment]
@garymcnulty thanks for filing and sorry it took so long to look into this. I found a race condition which may have caused this issue.  Let me know if you continue to see the problem after updating!
