### ISSUE TITLE
Bookmarks disappear sometimes on file save

### ISSUE THREAD

**Issue by hmsww** [JeffryBooher/brackets-bookmarks-extension#14]
Bookmarks disappear sometimes on file save

**Comment by JeffryBooher** [comment]
@hmsww thanks for filing. I believe this is fixed in the new version. Let me know if you continue to see this after the update.

**Comment by hmsww** [comment]
works great
wishlist for named bookmarks

**Comment by JeffryBooher** [comment]
you should file another issue as a feature request
