### ISSUE TITLE
Visually indicate

### ISSUE THREAD

**Issue by thany** [JeffryBooher/brackets-bookmarks-extension#20]
I'd be helpful to visually indicate on a line number when it's a bookmark. It makes it easier to glance at a file and see where the bookmarks are, if any at all. It also provides a visual feedback that tells the user toggling a bookmark actually worked.

I was about to uninstall this extension because I thought it didn't work, because toggling a bookmark didn't appear to do anything whatsoever. But it turns out it just doesn't show anything.

So that's why I'm asking.

Perhaps display an asterisk or something next to a line number, or reverse its background/foreground colours. As long as it's _something_ to indicate the presence of a bookmark.

**Comment by JeffryBooher** [comment]
Hmmmm the extension should highlight the line that is bookmarked.  Do you have a theme selected? What happens if you select the "Dark" theme? or the "Light" theme?

**Comment by thany** [comment]
When activating the default Dark theme, I can see the purple backgrounded, white bookmark icon for a bookmarked line, but *only* when that line is the current line. When the cursor is anywhere else, a bookmarked line only shows a white line number.

In the default Light theme, literally the same thing happens, so when a bookmarked line is not the current line, the line number is unreadable.

I'm using the [Soft Dark](https://github.com/Brackets-Themes/SoftDark) theme, where *no* indication is visible.

**Comment by JeffryBooher** [comment]
Thanks for letting me know. It looks like something has changed in `codemirror` recently.  If I turn off line numbers and turn them back on they show up on the wrong side of the code-folding which is a bug; probably unrelated but it looks like there was a change to the way gutters work in codemirror.  I will investigate and try to get a fix soon

**Comment by JeffryBooher** [comment]
@thany I think this should be fixed with #24. Let me know if you still see problems if you install version `0.10.5` over the extension from the registry.  Thanks for reporting!

**Comment by thany** [comment]
Yes, working a lot better now!

Only thing that's left, is the current line behaviour. While the bookmark does actually show now, when it's also the current line (and current line highlighting is enabled) it's completely hidden again.

Oh and maybe do something about the font colour as well? Not that important though.

See:
![1](https://cloud.githubusercontent.com/assets/152227/18127246/720b7734-6f7f-11e6-9aea-5ec4f6720147.PNG) ![2](https://cloud.githubusercontent.com/assets/152227/18127253/78bf2134-6f7f-11e6-9f2c-a22f1526faab.PNG)

**Comment by JeffryBooher** [comment]
@thany that looks like it may be the theme you are using. Does it happen with the built in Dark theme?  I may not be able to fix that.

![active line](https://cloud.githubusercontent.com/assets/1514099/18139536/d7801354-6f66-11e6-8b66-24fc97307f9e.png)

**Comment by JeffryBooher** [comment]
@thany Closing this as UTR. Feel free to reopen if you have more data. Thanks!
