### ISSUE TITLE
Failed to install in italian locale: misspelled locale file name

### ISSUE THREAD

**Issue by arofab** [JeffryBooher/brackets-bookmarks-extension#25]
The italan locale file should be named 'nls/it/strings.js' instead of 'nls/it/string.js'

**Comment by JeffryBooher** [comment]
ugh...Thanks for catching.

**Comment by JeffryBooher** [comment]
Should be fixed now with #26

**Comment by JeffryBooher** [comment]
Let me know if you still see an issue

**Comment by arofab** [comment]
The extension installs now.
Many thanks!
