### ISSUE TITLE
Request: add a shortcut to show/hide the bookmarks panel

### ISSUE THREAD

**Issue by asnowfix** [JeffryBooher/brackets-bookmarks-extension#8]
Currently, we need to navigate View > Show Bookmarks Panel. It would be nice to have a shortcut
1. Right-column icon to toggle visibility, like many other brackets extensions
2. Keyboard shortcut (Ctrl+Shift+B ?)

**Comment by arturoSoto** [comment]
You can define/override default key bindings in your keymap.json file.
Navigate to Debug > Open User Key Map and add your custom key bindings. ([Oficial documentation](https://github.com/adobe/brackets/wiki/User-Key-Bindings))
E.g.
"Ctrl-Shift-B": "bracketsEditorBookmarks.toggleBookmarksPanel"
