### ISSUE TITLE
Bookmarks should  still show even when line is selected

### ISSUE THREAD

**Issue by gmaggio** [JeffryBooher/brackets-bookmarks-extension#9]
**Bookmarks** _(with background colour and icon)_ should still show **even when the cursor is in the bookmarked lines**. Currently it uses **highlighted line number** to indicate that the current line is bookmarked. This has certain shortcomings:

- It's too subtle
- It's difficult to distinguish

Thus one may think it's not yet bookmarked and try to re-bookmark it.
So I would suggest to maintain the colouring and the icon even when the cursor is on that line.

Cheers.

**Comment by anephew** [comment]
+1 

Jeff, fix this please

**Comment by JeffryBooher** [comment]
@gmaggio @anephew can either of you provide a screen grab? 

Here is what I see:

![bm_default](https://cloud.githubusercontent.com/assets/1514099/6111151/a3369302-b03b-11e4-869d-6fdbf96e4da9.png)
![bm_dark](https://cloud.githubusercontent.com/assets/1514099/6111152/a3394f5c-b03b-11e4-9056-bab367881bd1.png)

**Comment by gmaggio** [comment]
Here is what I see:

> NOTE: Notice where the **cursor** is

1. Cursor **NOT in the same line** as the bookmark
![brackets_bookmarks_1-cursor-not-in-same-line](https://cloud.githubusercontent.com/assets/127763/6120181/f38dd5e4-b104-11e4-9802-61851da2e178.jpg)

2. Cursor **in the same line** as the bookmark
![brackets_bookmarks_2-cursor-in-same-line](https://cloud.githubusercontent.com/assets/127763/6120180/f38ca336-b104-11e4-9704-39aac293a085.jpg)

3. Cursor in the same line as the bookmark but made a **selection**
![brackets_bookmarks_3-cursor-in-same-line-but-in-selection](https://cloud.githubusercontent.com/assets/127763/6120182/f390e1da-b104-11e4-8afb-5701bcb8081f.jpg)

> Notice how in sample **number 2** the bookmark disappears but reappears if you make a selection.

**Comment by gmaggio** [comment]
Okay, it seems that this issue only occurs if I enabled **'Highlight Active Line'** (under **View**). If I disabled it, the bookmark doesn't disappear.

**Comment by JeffryBooher** [comment]
ah, good catch. I will fix that @gmaggio!  Also it looks like the line may be off with the code-folding extension as well.  I will look into that. Thanks!

**Comment by JeffryBooher** [comment]
@gmaggio @anephew this issue should now be resolved with the latest update.
